name: autoAction
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        continue-on-error: true
        run: |
          echo -e '\n-------------------------------------------------\n'
          echo -e '\nhttp://122.224.218.18:9999/\n'
          curl -i -s -k --compressed -m 10 -X $'GET' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H $'Accept-Encoding: gzip, deflate' -H $'Accept-Language: zh-CN,zh;q=0.9' -H $'Connection: close' -H $'Upgrade-Insecure-Requests: 1' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' -d $'' $'http://122.224.218.18:9999/'
          echo -e '\n-------------------------------------------------\n'
